name: Scrape MoneyControl Daily

# on:
#   schedule:
#     - cron: "0 10 * * *"  # Runs every day at 10:00 AM UTC
  # workflow_dispatch:     # Optional: lets you trigger manually

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          GOOGLE_SERVICE_ACCOUNT_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          RANGE: ${{ secrets.RANGE }}
        run: node src/scrapeMoneyControl.js
